### ISSUE TITLE
Laravel 5 support?

### ISSUE THREAD

**Issue by vadimwe** [sebklaus/profiler#16]

**Comment by vadimwe** [comment]
Any news? Very useful package.

**Comment by sebklaus** [comment]
@vadimwe I'm glad you find this package useful!
Unfortunately I'm flat out at work at the moment. On my own projects I swapped to [Laravel Debugbar](https://github.com/barryvdh/laravel-debugbar/) to get pretty much all the functionality of Profiler. Maybe it's also an alternative for your needs.

**Comment by vadimwe** [comment]
Thank you for fast reply!

Yes, I use package you recommend, but yours I like much better.
