### ISSUE TITLE
fresh install error

### ISSUE THREAD

**Issue by weboAp** [sebklaus/profiler#3]
exception 'ErrorException' with message 'Missing argument 1 for Sebklaus\Profiler\Providers\ProfilerServiceProvider::{closure}()' in /vendor/sebklaus/profiler/src/Sebklaus/routes.php:6

**Comment by sebklaus** [comment]
Thanks for submitting this issue.
Could you just quickly answer the below to help me find out, what happened?
1. PHP version
2. Laravel version
3. URL you were trying to access

In the meantime, I have already changed the way the `/_profiler` wildcard route is added.
It now only gets registered, if the `urlToggle` option is active.

Cheers

**Comment by sebklaus** [comment]
Assumed resolved.
