### ISSUE TITLE
Environment config not loading

### ISSUE THREAD

**Issue by russback** [sebklaus/profiler#4]
Hi

Just switched from the legacy juy profiler and I'm finding that my config doesn't load:

app/config/local/packages/sebklaus/profiler/config.php

Has this:

```
return array(

    // Set to TRUE to enable profiling, FALSE to disable. NULL to listen to the app.debug value (default)
    'profiler' => TRUE,

);
```

This should override the default (production) value of FALSE, but the config file isn't loading.

Am I missing something?

Thanks

**Comment by sebklaus** [comment]
Hi russback,

the path you described `app/config/local/packages/sebklaus/profiler/config.php` targets the `local` environment only.

The correct path should be `app/config/packages/sebklaus/profiler/config.php`.

Let me know, if this fixes your issue.

Cheers,
Seb

**Comment by russback** [comment]
Yes that's my point. This should enable it on the local environment but it doesn't - I can only enable it by editing the production config

**Comment by sebklaus** [comment]
Ah, OK! I think I get it now.

There is no need to have the config in multiple spots. `app/config/packages/sebklaus/profiler/config.php` covers all environments. Also, as you correctly noticed, it doesn't work, when you duplicate the config in an `app/[environmentName]` folder.

The easiest way to activate Profiler for different environments is to have different `app.php` files and set the value for `debug` to `TRUE`, while leaving  the value of `profiler` as `NULL`.

Alternatively, if you don't want to activate `debug` in your environment, you can set the value of `urlToggle` to `TRUE` and add `/_profiler` to any URL to activate Profiler. It will stay active in your current session.

I hope all this makes sense. Let me know, if you run into any more issues!

Cheers,
Seb

**Comment by russback** [comment]
I haven’t actually added a ‘profiler’ value to app.php - it’s all in packages/sebklaus/profiler/config.php. Are you saying the array in that file should be in app.php?

**Comment by sebklaus** [comment]
No, let me try and make it a bit clearer, than in my previous comment:

`app/config/packages/sebklaus/profiler/config.php` is the correct and only spot to have all Profiler related config settings. It's the default spot where the config resides after `php artisan config:publish`.

Your `app/config/app.php` includes the `debug` option. Profiler checks the value of that option to activate.
If `debug` in `app/config/app.php` is set to `true`, Profiler will be active in your `production` environment.
If you have an environment called `local`, for example, Profiler would check the value of `debug` in  `app/config/local/app.php`.

If you want Profiler to activate regardless of the environment or `debug` value, just change the value of `profiler` to `TRUE` in `app/config/packages/sebklaus/profiler/config.php`. Profiler will now always be active, in any environment.

Hope this clears things up a bit.

Cheers,
Seb

**Comment by russback** [comment]
OK thanks, will give that a go!
