### ISSUE TITLE
Error: Using $this when not in object context

### ISSUE THREAD

**Issue by ls-michielrensen** [sebklaus/profiler#8]
The issue is in file: vendor/sebklaus/profiler/src/Sebklaus/routes.php

Maybe use the the App facade there will fix this issue?

**Comment by erinnovations** [comment]
+1

**Comment by sebklaus** [comment]
Hi michielrensen &  erinnovations,

thanks for pointing out this issue. It never occurred for me, but I have switched to using only facades, instead of a mix, in https://github.com/sebklaus/profiler/commit/bffed055d0c367812430689518c4c92cb830d2c1.

It tested fine in my apps, please re-open, if you run into any more problems.

Cheers,
Seb

**Comment by erinnovations** [comment]
Thanks for the fast response! And thank you to continue this great profiler!

**Comment by ls-michielrensen** [comment]
Thanks a lot for fixing this so quickly, it works like a charm!

**Comment by sebklaus** [comment]
Thanks for taking the time to come back here and leave feedback, much appreciated!
Glad everything works again for you.

Cheers,
Seb

**Comment by ls-michielrensen** [comment]
No worries!

I’m running into an issue now which has something to do with my application setup and not with your profiler. Apparently my defined routes are executed (or considered) _before_ the one in your routes.php. I have in there one route which checks for ’static’ pages from the root 

Route::get('{page}', 'PageController@getView’);

I guess it’s a matter of the order in which the routes are considered. I can _copy_ your logic into my routes file and it’ll work, but it’s not really maintainable. Maybe you have the golden tip? :)

Cheers,

Michiel

**Comment by sebklaus** [comment]
I also ran into a minor issue with the routes in one of my apps, but it wasn't vital for me at the time.
Let me look into it and think about possible other ways to get the URL enabling/ disabling working.

**Comment by ls-michielrensen** [comment]
Maybe toggle it by using a GET-parameter?

**Comment by sebklaus** [comment]
> Maybe toggle it by using a GET-parameter?

I'd like to try something more trivial first. Would you mind giving the [routesFix](https://github.com/sebklaus/profiler/tree/routesFix) branch a go? I simply changed the used "wildcard" variable name from `path` to `profilerPath`.
Maybe Laravel doesn't like the fact that two routes try to use the same "wildcard".

**Comment by ls-michielrensen** [comment]
I don’t mind doing that, but than I have a silly question, how do I do that using composer? :)

**Comment by sebklaus** [comment]
Not a silly question at all!
Just change 'dev-master' to 'dev-routesFix' for sebklaus/profiler.

**Comment by ls-michielrensen** [comment]
I’ve tried the other branch, but I still have the same issue.

The pagecontroller returns a 404 if the page ‘_profiler’ cannot be found. 

See the attached screenshot for an overview of my routes.

I appreciate it a lot that you’re picking this up so quick!

Btw, I can toggle the profiler by going to /about/_profiler (because that page does exist).

**Comment by sebklaus** [comment]
Looks like the attachment didn't make it into Github from the Email.
Would you be able to include it via the website?

I'll have to call it a day for today. Less than five hours and I have to get ready for work again! I'll have a look, once I get to the office, if you can get that screenshot attached. And maybe also write down for which routes you get the 404 error when adding '_profiler' to the end.

Cheers,
Seb

**Comment by ls-michielrensen** [comment]
Here it is: 

![screen shot 2013-12-10 at 16 57 53](https://f.cloud.github.com/assets/1837560/1715665/584b2116-61b6-11e3-86e6-5206530461bc.png)

Basically the urlToggle works if I append _profiler to an (non)existing 'page': /test/_profiler (non-existing page, redirects to 404 of course), /about/_profiler (existing page, redirects to page) both with the profiler enabled. The toggle doesn't work for /_profiler/ calls because apparently it conflicts with my routes.

I can use the toggle, so I'm not in a rush :)

Cheers

**Comment by ls-michielrensen** [comment]
Higher quality screenshot:

![screen shot 2013-12-10 at 16 57 53](https://f.cloud.github.com/assets/1837560/1715816/0edf360a-61b8-11e3-96b9-5309b4cc1d35.png)

**Comment by sebklaus** [comment]
Hi,
I see what you mean, now! You're right, urlToggle won't work for your root route (i.e. http://foo/_profiler), because there are two wildcard routes configured and yours trumps the Profiler one, as it should do.

As I mentioned before, I'll try and come up with a different implementation of the feature, but until then, I'm afraid it won't work on your root route. I'm very sorry for the inconvenience.

Cheers,
Seb

**Comment by ls-michielrensen** [comment]
Ah don't worry, it's meant to be used by me or another developer anyway, they should know what works and what doesn't :) 
I'll see if I can come up with something.
