### ISSUE TITLE
Route names

### ISSUE THREAD

**Issue by MaatwebsiteSupport** [sebklaus/profiler#9]
When viewing the routes inside the profiler, the route names are missing. Now only the array index is shown (integers).

I think `$name` should be changed into: `$route->getName()`, inside `_routes.blade.php`

**Comment by sebklaus** [comment]
Hi Maatwebsite,

Thanks for sending in the issue.
Would you be able to tell me, if you run Laravel 4.0 or 4.1?

Cheers,
Seb

**Comment by MaatwebsiteSupport** [comment]
4.1

**Comment by sebklaus** [comment]
Hi @Maatwebsite,

thanks for the quick reply. https://github.com/sebklaus/profiler/commit/4a8e71e8b9a8b409071f5d0793da0d6ec8ff6a57 should fix the issue.
Let me know, if there is anything else.

Cheers,
Seb

**Comment by MaatwebsiteSupport** [comment]
Great! Thanks!
